[project]
name = "dad-jokes-mcp"
version = "1.0.0"
description = "A lightweight MCP server for dad jokes from icanhazdadjoke.com"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=0.1.0",
    "smithery>=0.1.0",
    "httpx>=0.27.0",
]

[tool.smithery]
server = "server:create_server"